# Generated by Django 4.2.2 on 2023-06-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OtpCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=128, verbose_name="شماره تلفن"),
                ),
                ("code", models.PositiveSmallIntegerField()),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
