# Generated by Django 4.2.2 on 2023-06-24 08:26

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_otpcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otpcode",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None, unique=True, verbose_name="شماره تلفن"
            ),
        ),
    ]
