# Generated by Django 4.2.2 on 2023-06-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_otpcode_options_alter_otpcode_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="فعال"),
        ),
    ]
