# Generated by Django 4.2.2 on 2023-06-25 08:54

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_user_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128,
                        region=None,
                        unique=True,
                        verbose_name="شماره تلفن",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True,
                        max_length=60,
                        null=True,
                        verbose_name="نام و نام خانوادگی",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ثبت"),
                ),
                ("otp_code", models.CharField(max_length=8, null=True)),
                ("password", models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
