# Generated by Django 4.2.3 on 2023-08-21 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_otpcode_delete_pendinguser_user_auth_method_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="فعال"),
        ),
    ]
